logging:
  level:
    com:
      journalmicroservice:
        JournalMicroService: TRACE
spring:
  config:
    import:
      - configserver:http://localhost:8085
  profiles:
    active:
      - dev
server:
  port: 8082


