server:
  port: 8084

spring:
  cloud:
    gateway:
      routes:
        - id: AUTHSERVICE
          uri: http://localhost:8087/auth
          predicates:
            - Path=/auth/**

        - id: IMAGESERVICE
          uri: lb://IMAGEMICROSERVICE
          predicates:
            - Path=/image/**

        - id: JOURNALSERVICE
          uri: lb://JOURNALMICROSERVICE
          predicates:
            - Path=/journal/**
          filters:
            - AuthFilter

        - id: USERSERVICE
          uri: lb://USERMICROSERVICE
          predicates:
            - Path=/user/**
          filters:
            - AuthFilter

        - id: INVITATIONSERVICE
          #            uri: lb://INVITATIONSERVICE
          uri: http://localhost:8086/invitation
          predicates:
            - Path=/invitation/**
          filters:
            - AuthFilter



eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

